package ru.tbank.practicum.enums;

public enum EventType {
    RADIATOR_TEMPERATURE_SET,
    RADIATOR_ONLINE,
    RADIATOR_OFFLINE,
    RADIATOR_BROKEN,
    RADIATOR_RESTORED,
    BLINDS_OPENED,
    BLINDS_CLOSED,
    BLINDS_HALF_OPENED,
    BLINDS_ONLINE,
    BLINDS_OFFLINE,
    BLINDS_BROKEN,
    BLINDS_RESTORED,
    RULE_APPLIED,
    SCHEDULE_APPLIED
}
