weather:
  base-url: "https://api.openweathermap.org"
  api-key: "e1572cabddc662b38654338d33d67415"
  city: "Saratov"
  poll-interval: 30m

logging:
  level:
    ru.tbank.practicum: DEBUG

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/homeapp
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml