apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-app
spec:
  type: {{ .Values.app.service.type }}
  selector:
    app: {{ .Chart.Name }}-app
  ports:
    - name: http
      port: {{ .Values.app.service.port }}
      targetPort: 8080
