apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-app
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-app
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-app
    spec:
      containers:
        - name: app
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Djava.net.preferIPv4Stack=true -Djava.net.preferIPv6Addresses=false"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://{{ .Chart.Name }}-postgres:5432/{{ .Values.postgres.database }}
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: POSTGRES_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: POSTGRES_PASSWORD
            - name: SPRING_LIQUIBASE_ENABLED
              value: "false"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: {{ .Chart.Name }}-kafka:9092
            - name: OPENROUTER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: OPENROUTER_API_KEY
            - name: TELEGRAM_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: TELEGRAM_BOT_TOKEN
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 80
            periodSeconds: 20
