apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Chart.Name }}-migrations
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  backoffLimit: 10
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: liquibase
          image: "{{ .Values.migrations.image.repository }}:{{ .Values.migrations.image.tag }}"
          imagePullPolicy: {{ .Values.migrations.image.pullPolicy }}
          env:
            - name: LIQUIBASE_COMMAND_URL
              value: jdbc:postgresql://{{ .Chart.Name }}-postgres:5432/{{ .Values.postgres.database }}
            - name: LIQUIBASE_COMMAND_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: POSTGRES_USER
            - name: LIQUIBASE_COMMAND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Chart.Name }}-secret
                  key: POSTGRES_PASSWORD
          command:
            - /bin/sh
            - -c
          args:
            - |
              echo "Waiting for PostgreSQL...";
              until liquibase --search-path=/liquibase/changelog --changelog-file=db.changelog-master.yaml status >/dev/null 2>&1; do
                echo "PostgreSQL is not ready yet";
                sleep 5;
              done

              echo "Running Liquibase migrations...";
              liquibase --search-path=/liquibase/changelog --changelog-file=db.changelog-master.yaml update
